# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /media/data/Unreal Engine/Linux_Unreal_Engine_5.3.1
GAMEPROJECTFILE =/media/data/Projects/deadly-wheels/DeadlyWheels.uproject

TARGETS = \
	DeadlyWheels-Linux-DebugGame  \
	DeadlyWheels-Linux-Shipping  \
	DeadlyWheels \
	DeadlyWheelsEditor-Linux-DebugGame  \
	DeadlyWheelsEditor-Linux-Shipping  \
	DeadlyWheelsEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend DeadlyWheelsEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug DeadlyWheelsEditor-Linux-Debug


DeadlyWheels-Linux-DebugGame:
	 $(PROJECTBUILD) DeadlyWheels Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DeadlyWheels-Linux-Shipping:
	 $(PROJECTBUILD) DeadlyWheels Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DeadlyWheels:
	 $(PROJECTBUILD) DeadlyWheels Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DeadlyWheelsEditor-Linux-DebugGame:
	 $(PROJECTBUILD) DeadlyWheelsEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DeadlyWheelsEditor-Linux-Shipping:
	 $(PROJECTBUILD) DeadlyWheelsEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DeadlyWheelsEditor:
	 $(PROJECTBUILD) DeadlyWheelsEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
